Docker compose structure is now network/support/app

diff --git a/docker/network/ep1/Dockerfile b/docker/network/ep1/Dockerfile
--- a/docker/network/ep1/Dockerfile
+++ b/docker/network/ep1/Dockerfile
@@ -50,20 +50,15 @@ RUN mkdir -p /home/app/endpoint/tmp/pids; \
     mkdir -p /home/app/endpoint/util/files
 
 
-# Copy import files
-#
-ADD import/* /home/app/endpoint/util/files/
-
-
 # Run endpoint software
 #
 WORKDIR /home/app/endpoint
 RUN bundle install --path vendor/bundle
 
 
-# Configure mongo port (db at ‘database:27017’, instead of local install)
+# Configure mongo port (db at ‘ep1db:27017’, instead of local install)
 #
-RUN sed -i -e "s/localhost:27017/database:27017/" config/mongoid.yml
+RUN sed -i -e "s/localhost:27017/ep1db:27017/" config/mongoid.yml
 
 
 # Change back to root
@@ -79,9 +74,17 @@ RUN echo "#" >> /root/.bashrc
 RUN echo "cd /home/app/endpoint" >> /root/.bashrc
 
 
-# Copy endpoint startup script and make it executable
+# Create endpoint startup script and make it executable
 #
-ADD scripts/endpoint.sh /etc/service/endpoint/run
+RUN mkdir -p /etc/service/endpoint
+RUN echo "#!/bin/bash" >> /etc/service/endpoint/run
+RUN echo "#" >> /etc/service/endpoint/run
+RUN echo "# Halt on errors" >> /etc/service/endpoint/run
+RUN echo "set -e -x -o nounset" >> /etc/service/endpoint/run
+RUN echo "" >> /etc/service/endpoint/run
+RUN echo "# Run hub as app user" >> /etc/service/endpoint/run
+RUN echo "#" >> /etc/service/endpoint/run
+RUN echo "chpst -u app bash -c 'export PATH=$PATH:/usr/local/bin; cd /home/app/endpoint/; ./runme.sh'" >> /etc/service/endpoint/run
 RUN chmod +x /etc/service/endpoint/run
 
 
diff --git a/docker/network/hub/Dockerfile b/docker/network/hub/Dockerfile
--- a/docker/network/hub/Dockerfile
+++ b/docker/network/hub/Dockerfile
@@ -5,7 +5,7 @@
 FROM phusion/passenger-ruby19
 
 
-# ENV - Set non-interactive shell and disable policy-rc.d
+# Set non-interactive shell and disable policy-rc.d
 #
 ENV DEBIAN_FRONTEND noninteractive
 RUN sed -i -e "s/exit 101/exit 0/" /usr/sbin/policy-rc.d
@@ -14,7 +14,7 @@ RUN sed -i -e "s/exit 101/exit 0/" /usr/sbin/policy-rc.d
 # Install applications from repos
 #
 RUN apt-get update; \
-    apt-get --yes install ntp libxslt-dev libxml2-dev lynx
+    apt-get install -y libxslt-dev libxml2-dev lynx
 
 
 # ENV and User
@@ -31,9 +31,9 @@ RUN git clone https://github.com/physiciansdatacollaborative/hub.git; \
 
 
 WORKDIR /home/app/hub
-RUN bundle install --path vendor/bundle; \
-    mkdir -p /home/app/hub/tmp/pids; \
-    sed -i -e "s/localhost:27017/database:27017/" config/mongoid.yml
+RUN bundle install --path vendor/bundle
+RUN mkdir -p /home/app/hub/tmp/pids
+RUN sed -i -e "s/localhost:27017/hubdb:27017/" config/mongoid.yml
 
 
 # Change back to root
@@ -52,9 +52,17 @@ RUN echo "Add to PATH"
 RUN echo "export PATH=$PATH:/usr/local/bin"
 
 
-# Copy hub startup script and make it executable
+# Create hub startup script and make it executable
 #
-ADD scripts/hub.sh /etc/service/hub/run
+RUN mkdir -p /etc/service/hub
+RUN echo "#!/bin/bash" >> /etc/service/hub/run
+RUN echo "#" >> /etc/service/hub/run
+RUN echo "# Halt on errors" >> /etc/service/hub/run
+RUN echo "set -e -x -o nounset" >> /etc/service/hub/run
+RUN echo "" >> /etc/service/hub/run
+RUN echo "# Run hub as app user" >> /etc/service/hub/run
+RUN echo "#" >> /etc/service/hub/run
+RUN echo "chpst -u app bash -c 'export PATH=$PATH:/usr/local/bin; cd /home/app/hub/; ./runme.sh'" >> /etc/service/hub/run
 RUN chmod +x /etc/service/hub/run
 
 
