Hub and Endpoints will now only work over autossh tunnels

diff --git a/docker/extras/endpoint/Dockerfile b/docker/extras/endpoint/Dockerfile
--- a/docker/extras/endpoint/Dockerfile
+++ b/docker/extras/endpoint/Dockerfile
@@ -13,7 +13,10 @@ ENV BRANCH pdc-0.1.0
 # Update (non-interactive) and install packages
 #
 ENV DEBIAN_FRONTEND noninteractive
-RUN apt-get update; apt-get install -y lynx unzip
+RUN apt-get update; apt-get install -y \
+      autossh \
+      lynx \
+      unzip
 
 
 # Clone repo, assign to app
@@ -33,17 +36,61 @@ RUN /sbin/setuser app bundle install --path vendor/bundle
 RUN sed -i -e "s/localhost:27017/epdb:27017/" config/mongoid.yml
 
 
-# Create Endpoint startup script and make it executable
+# Create startup script and make it executable
 #
-RUN mkdir -p /etc/service/endpoint
+RUN mkdir -p /etc/service/app
 RUN ( \
       echo "#!/bin/bash"; \
+      echo "#"; \
+      echo "# Exit on errors or unitialized variables"; \
+      echo "#"; \
+      echo "set -e -o nounset"; \
       echo ""; \
+      echo "# Wait until SSH keys are ready"; \
+      echo "#"; \
+      echo "while [ -f /app/wait ]"; \
+      echo "do"; \
+      echo "  sleep 10"; \
+      echo "done"; \
+      echo ""; \
+      echo "# Start tunnel"; \
+      echo "#"; \
       echo "cd /app"; \
-      echo "exec /sbin/setuser app './runme.sh'"; \
+      echo "export AUTOSSH_PIDFILE=/app/tmp/pids/autossh.pid"; \
+      echo "export REMOTE_PORT=\`expr 40000 + \${gID}\`"; \
+      echo "/usr/bin/autossh -M0 -p2774 -N -R \${REMOTE_PORT}:localhost:3001 autossh@\${HUB} -o ServerAliveInterval=15 -o ServerAliveCountMax=3 -o Protocol=2 -o ExitOnForwardFailure=yes &"; \
+      echo "sleep 5"; \
+      echo ""; \
+      echo "# Start Endpoint"; \
+      echo "#"; \
+      echo "exec /sbin/setuser app '/app/runme.sh'"; \
     )  \
-    >> /etc/service/endpoint/run
-RUN chmod +x /etc/service/endpoint/run
+    >> /etc/service/app/run
+RUN chmod +x /etc/service/app/run
+
+
+# Create key exchange script, uses a wait file (/app/wait)
+#
+RUN ( \
+      echo "#!/bin/bash"; \
+      echo "#"; \
+      echo "# Exit on errors or unitialized variables"; \
+      echo "#"; \
+      echo "set -e -o nounset"; \
+      echo ""; \
+      echo "# Create an SSH key and exchange it"; \
+      echo "#"; \
+      echo "ssh-keygen -t rsa -f /root/.ssh/id_rsa -q -N \"\""; \
+      echo "scp -P 2774 -p /root/.ssh/id_rsa.pub pdcadmin@\${HUB}:/tmp/endpoint_id_rsa.pub"; \
+      echo "ssh -p 2774 -t pdcadmin@\${HUB} \"sudo su - autossh -c 'cat /tmp/endpoint_id_rsa.pub >> /home/autossh/.ssh/authorized_keys'\""; \
+      echo ""; \
+      echo "# Remove the hold on Endpoint startup"; \
+      echo "#"; \
+      echo "rm /app/wait"; \
+    )  \
+    >> /app/key_exchange.sh
+RUN chmod +x /app/key_exchange.sh
+RUN touch /app/wait
 
 
 # Run initialization command
